const goodKitty
const goodPuppy
const bigDog
const smallCat
const redRose
const blueSky
const greenTree
const whiteCloud
const blackCar
const redBike
const hotTea
const coldWater
const freshMilk
const sweetCake
const bigHouse
const smallRoom
const newBook
const oldBook
const fastCar
const slowBike
const highScore
const lowScore
const maxMark
const minMark
const firstPlace
const secondPlace
const thirdPlace
const bestFriend
const goodFriend
const newFriend
const oldFriend
const happyDay
const goodDay
const badDay
const sunnyDay
const rainyDay
const schoolBus
const cityBus
const trainName
const flightName
const shopName
const bankName
const parkName
const beachName
const riverName
const treeName
const flowerName
const starName