let colorBlue
let colorRed
let colorGreen
let colorBlack
let colorWhite
let colorYellow
let colorPink
let colorOrange
let foodName
let fruitName
let foodPrice
let foodCount
let bookName
let bookPrice
let pageCount
let pageNumber
let markTotal
let markScore
let markGrade
let testName
let testScore
let gameLevel
let gamePoint
let gameLife
let playerName
let playerScore
let teamScore
let teamPoint
let carName
let carModel
let carPrice
let bikeName
let bikeModel
let bikePrice
let roomName
let roomSize
let roomNumber
let doorNumber
let houseNumber
let streetName
let cityName
let stateName
let countryName
let dayName
let monthName
let yearNumber
let currentTime
let currentDate