arrow functions 
let add = (a, b) => a + b;
let subtract = (a, b) => a - b;
let multiply = (a, b) => a * b;
let divide = (a, b) => a / b;
let square = n => n * n;
let cube = n => n * n * n;
let double = n => n * 2;
let triple = n => n * 3;
let half = n => n / 2;
let increment = n => n + 1;
let decrement = n => n - 1;
let greet = name => "Hello " + name;
let welcome = name => "Welcome " + name;
let isEven = n => n % 2 === 0;
let isOdd = n => n % 2 !== 0;
let isPositive = n => n > 0;
let isNegative = n => n < 0;
let isAdult = age => age >= 18;
let getLength = text => text.length;
let upper = text => text.toUpperCase();
let lower = text => text.toLowerCase();
let firstChar = text => text[0];
let lastChar = text => text[text.length - 1];
let addTen = n => n + 10;
let subtractTen = n => n - 10;
let multiplyByFive = n => n * 5;
let divideByFive = n => n / 5;
let percentage = (mark, total) => (mark / total) * 100;
let simpleInterest = (p, r, t) => (p * r * t) / 100;
let areaRectangle = (l, w) => l * w;
let perimeterRectangle = (l, w) => 2 * (l + w);
let areaSquare = side => side * side;
let perimeterSquare = side => 4 * side;
let areaTriangle = (b, h) => (b * h) / 2;
let speed = (distance, time) => distance / time;
let distance = (speed, time) => speed * time;
let time = (distance, speed) => distance / speed;
let profit = (sp, cp) => sp - cp;
let loss = (cp, sp) => cp - sp;
let max = (a, b) => a > b ? a : b;
let min = (a, b) => a < b ? a : b;
let average = (a, b) => (a + b) / 2;
let power = (a, b) => a ** b;
let remainder = (a, b) => a % b;
let fullName = (first, last) => first + " " + last;
let ageAfterFiveYears = age => age + 5;
let priceWithDiscount = (price, discount) => price - (price * discount / 100);